# Generated by Django 3.2.23 on 2024-06-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='em_conta',
            field=models.BooleanField(default=False),
        ),
    ]
