# Generated by Django 3.2.23 on 2024-06-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20240608_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cod_venda',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
