# Generated by Django 3.2.23 on 2024-06-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_alter_venda_cod_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandeira',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='operadora',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
