# Generated by Django 3.2.23 on 2024-06-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_auto_20240613_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atualizacao',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='atualizacao',
            name='data_inicio',
        ),
    ]
